apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: nightly-snapshot-generator
  labels:
    build.appstudio.redhat.com/pipeline: "nightly-snapshot-generator"
spec:
  params:
    - name: PATTERN
      type: string
      default: "scheduled"
  results:
    - name: COMPARE_RESULT
      value: "$(tasks.compare.results.TEST_OUTPUT)"
  tasks:
    - name: compare
      params:
        - name: PATTERN
          value: "$(params.PATTERN)"
      taskSpec:
        description: check to see if pipelinerun has PATTERN in it
        params:
          - name: PATTERN
            type: string
            description: pattern to match source-pipelinerun
        results:
          - name: COMPARE_RESULT
        steps:
          - name: compare
            image: registry.access.redhat.com/ubi8/ubi-minimal
            env:
              - name: PATTERN
                value: "$(params.PATTERN)"
              - name: SOURCE_PIPELINERUN
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['pac.test.appstudio.openshift.io/original-prname']
            script: |
              #!/usr/bin/env bash
              matches=$(echo "$SOURCE_PIPELINERUN" | grep "$PATTERN")
              if [ -n "$matches" ]; then
                echo "true" > $(results.compare_result.path)
              else
                echo "false" > $(results.compare_result.path)
              fi
